# Generated by Django 4.1.3 on 2022-11-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiskeyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Bourbon'), ('I', 'Irish'), ('R', 'Rye'), ('S', 'Scotch'), ('O', 'Other')], default='O', max_length=1)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=25)),
                ('subType', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.whiskeytypes')),
            ],
        ),
    ]
