# Generated by Django 4.1.3 on 2022-11-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_whiskey_user_alter_whiskey_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='image_url',
            field=models.CharField(default='some URL', max_length=200),
            preserve_default=False,
        ),
    ]
