# Generated by Django 4.1.3 on 2022-11-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_whiskey_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='similiar_product',
            field=models.ManyToManyField(to='main_app.whiskey'),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='image_url',
            field=models.CharField(default='https://s3-us-west-2.amazonaws.com/whiskeycollectorapp/a31ae1.png', max_length=200),
        ),
    ]
