# Generated by Django 4.1.3 on 2022-11-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_whiskey_similiar_product_alter_whiskey_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whiskey',
            old_name='similiar_product',
            new_name='similar_product',
        ),
    ]
